R specs
PromzzyKoncepts/School-Library pull request #7
Opened 2023-02-09 16:56 UTC by PromzzyKoncepts

# Hey There
> In this PR, we met the project requirements

### Project requirements
- Add unit tests for all the methods in all the classes:
  - `Book`
  - `Person`
  - `Student`
  - `Teacher`
  - `Classroom`
  - `Rental`

## KIndly Review

2023-02-09 18:44 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @PromzzyKoncepts, @belalgamal46 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 18:44 UTC, HAMMAS-SALEEM commented on spec/classroom_spec.rb
> +require_relative '../classroom'
![image](https://user-images.githubusercontent.com/93039359/217902519-2f7d6499-bbf8-4604-86c4-e6a3ce57e407.png)

- [ ] You didn't test **add_students** method shown in the image above :arrow_up: Kindly test this test to follow the requirements and fully test your classes :+1:

**Hint: You can see the below test to get an idea :arrow_down:**

```ruby
    it 'expect the classroom to have students' do
      student = Student.new(23, 'Maxwell', true)
      classroom.adding_students(student)
      expect(classroom.students).to eq [student]
    end
```

2023-02-09 18:44 UTC, HAMMAS-SALEEM commented on spec/person_spec.rb
> +    end
- [ ] When you create a person than a rental array is created :thinking: You didn't check that Kindly test your rentals array using the following code :arrow_down:

`expect(person.rentals).to eql []`

2023-02-09 18:44 UTC, HAMMAS-SALEEM commented on spec/person_spec.rb
> +
![image](https://user-images.githubusercontent.com/93039359/217905427-8503219e-8f08-4da7-ba7d-fe384e4b1b60.png)

- [ ] You didn't test the correct_name method shown in the image above :thinking: Kindly test it :+1: to fully test your person class :blush:

2023-02-09 18:44 UTC, HAMMAS-SALEEM commented on spec/person_spec.rb
> +    end
![image](https://user-images.githubusercontent.com/93039359/217905924-70655453-ded2-4675-b161-e8f23302dc30.png)

- [ ] You have tested this method :clap: but you didn't cover all the scenarios :fearful: means what if

1. The person doesn't have an age more than or equal to 18
2. The person doesn't have parent_permission true
3. The person doesn't have an age more than or equal to 18 and doesn't have parent_permission true

Kindly cover all the scenarios to fully test your classes with all the exceptional or expected cases :+1:

2023-02-09 18:44 UTC, HAMMAS-SALEEM commented on spec/student_spec.rb
> +  context 'with an input of names and ages' do
![image](https://user-images.githubusercontent.com/93039359/217907181-9d5d6864-46ef-4c86-b680-de631af198c8.png)

- [ ] You didn't test **play_hooky** method :fearful: Kindly test this method to test your student class fully :+1:

2023-02-10 09:37 UTC, gemmen29 approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 09:51 UTC, merged